# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myexample.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "myexample.Request" do
    optional :a, :string, 1
    optional :b, :string, 2
  end
  add_message "myexample.Response" do
    optional :value, :string, 1
  end
end

module Myexample
  Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("myexample.Request").msgclass
  Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("myexample.Response").msgclass
end
