# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: myexample.proto for package 'myexample'

require 'grpc'
require 'myexample_pb'

module Myexample
  module Engine
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'myexample.Engine'

      rpc :GetResponse, Request, Response
    end

    Stub = Service.rpc_stub_class
  end
end
